#!/bin/sh
cd ~
# user preferred settings

#cursor size
export XCURSOR_SIZE=20

# text editor
export MICRO_TRUECOLOR=1
export EDITOR=/usr/bin/micro

#browser
export BROWSER=librewolf
#terminal
export TERM=foot
#mail
export MAIL=thunderbird

# check /usr/local/bin/hyprstart 
